### ISSUE TITLE
Demander un accès à CREMMA

### ISSUE THREAD

**Issue by emchateau** [anrExperts/adire#5]
Comme le projet est mené en France, il est éligible pour disposer d’un compte sur Cremma.
https://cremmacall.sciencescall.org/

- [x] repérer les champs à renseigner dans le formulaire
- [x] préparer une candidature
- [x] envoyer la candidature

**Comment by sardinecan** [comment]
La [candidature](https://docs.google.com/document/d/1FqC3S80Qw6YM7tzhwlTNj6UEcUYhTx4pC6PyyuJN4Ps/edit) est presque prête. Il reste à la valider et à voir deux points que nous n'avons pas discuté (licence et plateforme pour le dépôt des données d'entrainement notamment).

**Comment by sardinecan** [comment]
@emchateau as-tu une préférence pour la licence et la plateforme utilisée pour la publication des données d'entraînement ?

Pour la plateforme, j'ai l'impression que Zenodo est privilégiée par rapport à Nakala pour les données HTR.
Concernant les licences, on trouve un peu de tout sur les jeux de données accessibles CC-BY-4, CC-BY-SA, CC-0, Apache 2.0, etc.

**Comment by emchateau** [comment]
Je ne vois pas vraiment pourquoi privilégier Zenodo. Nos images étant déjà sur Nakala il me paraît préférable de tout y verser.

En ce qui concerne les licences, je dirais qu’il n’y a pas vraiment de droit d’auteur. Simplement un droit sur les bases de données. Ce qui nous oriente plutôt vers des licences Creative Commons.

La question est de savoir si on choisit CC-BY ou bien CC-0.

**Comment by emchateau** [comment]
Actuellement on a mis CC-0 sur les images. Mais les contenus structurés (bdd et prosopographie) seront publiés en CC-BY. Il ne me semble pas que cela limite les réutilisations, simplement cela réclame une citation. C‘est à discuter tous ensemble en réunion (j’ajoute un tag).

**Comment by emchateau** [comment]
Cher @sardinecan, merci beaucoup pour ce document qui est très bien.
J'ai revu le document. Avec l’accord de @rcarvais, vous pouvez envoyer.

**Comment by sardinecan** [comment]
Candidature déposée le 2023-10-19

**Comment by emchateau** [comment]
+1
